import type { AiScenarioRead } from "../types";

const MEDAL = ["🥇", "🥈"];

function dirArrow(d: string): string {
  if (d === "up") return "▲";
  if (d === "down") return "▼";
  return "→";
}

/**
 * Renders the AI two-scenario read (ranked + scored + why-primary). INFO only.
 * Used both in the chart's floating 🤖 panel and inline in the Run-analysis result.
 */
export function ScenarioCard({ read }: { read: AiScenarioRead }) {
  const isAi = read.source === "ai";
  return (
    <div className="text-xs">
      <div className="mb-1.5 flex items-center gap-2">
        <span className="font-semibold text-violet-300">🤖 AI scenarios — {read.symbol}</span>
        <span
          className={`rounded px-1 py-0.5 text-[9px] font-semibold uppercase ${
            isAi ? "bg-violet-900/60 text-violet-200" : "bg-neutral-700 text-neutral-300"
          }`}
          title={isAi ? "Generated by the AI model" : "No AI model configured — deterministic map scenarios"}
        >
          {isAi ? "AI" : "rule-based"}
        </span>
      </div>

      {read.headline && (
        <div className="mb-2 rounded bg-neutral-800/60 px-2 py-1 text-center text-sm font-semibold text-neutral-100">
          {read.headline}
        </div>
      )}

      <div className="space-y-2">
        {read.scenarios.map((s, i) => {
          const primary = i === 0;
          return (
            <div
              key={i}
              className={`rounded border px-2 py-1.5 ${
                primary ? "border-violet-700/60 bg-violet-950/25" : "border-neutral-800 bg-neutral-900/40"
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="font-semibold text-neutral-100">
                  {MEDAL[i] ?? "•"} {s.label} <span className="text-neutral-500">{dirArrow(s.direction)}</span>
                </span>
                <span className={`font-bold tabular-nums ${primary ? "text-violet-200" : "text-neutral-300"}`}>
                  {s.prob}%
                </span>
              </div>
              {/* likelihood bar */}
              <div className="my-1 h-1 w-full overflow-hidden rounded bg-neutral-800">
                <div
                  className={primary ? "h-full bg-violet-400" : "h-full bg-neutral-500"}
                  style={{ width: `${Math.max(0, Math.min(100, s.prob))}%` }}
                />
              </div>
              {s.path && <div className="text-neutral-400">{s.path}</div>}
              {s.reasoning && <div className="mt-0.5 text-neutral-500">{s.reasoning}</div>}
            </div>
          );
        })}
      </div>

      {read.why_primary && (
        <div className="mt-2 rounded border border-violet-800/50 bg-violet-950/30 px-2 py-1 text-violet-200">
          <span className="font-semibold">Why “{read.primary}” is more likely: </span>
          {read.why_primary}
        </div>
      )}

      {read.invalidation && <div className="mt-2 text-amber-300">⚠ Invalidation: {read.invalidation}</div>}

      <div className="mt-2 border-t border-neutral-800 pt-1.5 text-[10px] text-neutral-600">
        {read.note} Info only — it does NOT change the engine's decision.
      </div>
    </div>
  );
}
